name: quicksort-springboot-build
run-name: quicksort-springboot-build run by ${{ github.actor }}
on:
  workflow_dispatch:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PACKAGES_USERNAME: ${{ github.repository.owner }}
      PACKAGES_PERSONAL_ACCESS_TOKEN_CLASSIC: ${{ secrets.PACKAGES_PERSONAL_ACCESS_TOKEN_CLASSIC }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          check-latest: true
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7
      - name: Build with Gradle 8.7
        run: gradle build
      - name: Publish boot jar
        run: gradle publishQuicksortSpringbootPublicationToGitHubPackagesQuicksortSpringbootRepository
      - name: Publish aws lambda zip
        run: gradle publishQuicksortSpringbootAwsLambdaPublicationToGitHubPackagesQuicksortSpringbootRepository

